### ISSUE TITLE
SSLErrorの発生

### ISSUE THREAD

**Issue by kanade9** [reud/PyLineNotify#1]
TOKENを取得して実行してみたところ、
requests.exceptions.SSLError: HTTPSConnectionPool(host='notify-api.line.me', port=443): Max retries exceeded with url: /api/notify (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
というエラーが発生してしまいました。

**Comment by reud** [comment]
ソースコードの提示をお願いします

**Comment by reud** [comment]
追記です

問題解決のため、Wifi環境(家か外か)や
試したこと などできるだけ多くの事を書いてください

**Comment by reud** [comment]
バグ報告は解決のために最低でもPythonのバージョン、ソースコード、実行環境(OSやIDE)、試したこと、エラーメッセージは載せてくれないと何にも進まないので....
エラーがこっちの状況で起こせるかも確認する必要があるし

**Comment by kanade9** [comment]
ソースコード:
import PyLineNotify
TOKEN = '********************MY_TOKEN************'
PyLineNotify.send_message(token=TOKEN,message='Hello World!')



エラー全文:
C:\ProgramData\Miniconda3\python.exe C:/Users/*******/PycharmProjects/Linenotify3(pic)/hoge1.py
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 248, in _get_conn
    return conn or self._new_conn()
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='notify-api.line.me', port=443): Max retries exceeded with url: /api/notify (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/**********/PycharmProjects/Linenotify3(pic)/hoge1.py", line 4, in <module>
    PyLineNotify.send_message(token=TOKEN,message='Hello World!')
  File "C:\ProgramData\Miniconda3\lib\site-packages\PyLineNotify\notifer.py", line 81, in send_message
    return notify.send_message(message)
  File "C:\ProgramData\Miniconda3\lib\site-packages\PyLineNotify\notifer.py", line 34, in send_message
    res = requests.post(URL, data=payload, headers=headers)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='notify-api.line.me', port=443): Max retries exceeded with url: /api/notify (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

Process finished with exit code 1






環境:
自宅の有線回線を用いて Miniconda3 Python 3.7.1 Pycharmで実行しています。

Pycharm側の設定はInterpreterをMiniconda3 python.exeにしており、Anaconda Prompt上でSSLに関するパッケージがあるかどうか確認したところpyOpenSSLがインストールされていました。

しかし最新版ではなかったためこれが原因であると思い、pyOpenSSLさらにはrequestsのアップデートを行いました。
しかしエラーの内容は変化がありませんでした。


ネットでは同じような問題が起きた際、対処法として
https://blog.cles.jp/item/10259
以上の記事のような方法が紹介されていて、PyLineNotifyではこの方法を使うことはできますか？

**Comment by reud** [comment]
Miniconda 3において同様の問題が確認されています
[参考](https://stackoverflow.com/questions/45908938/python-cant-connect-to-https-url-because-the-ssl-module-is-not-available)

斜め読みで要約をすると，Anaconda/Minicondaに内蔵されているSSLライブラリは独自の物となっているため，互換性がなくエラーを吐いているものだと考えられます．

解決方法としましては，Miniconda 3ではなくPure なPythonを入れるべきだと考えられます．
https://www.python.org/downloads/
こちらから好きなバージョンを選びインストールをしたあと，インストールしたPython.exeの場所をPyCharmのFile -> Settings -> project interpreter から右の歯車マークをクリックしてaddからPython.exeの場所を指定することで追加することができます．

参考までにPython.exeの場所は僕のWindows 10 の環境では，
C:\Users\<user>\AppData\Local\Programs\Python\Python37\python.exe
のように設定されています．(Python 3.7なのでpython37フォルダ)

もしもPureなPythonをインストールする場合は参考にしてください．

あ，インストール中にPATHを通すかみたいなチェックボックスがあったはずだけどそこチェック入れないと設定が大変面倒になるので気をつけてくださいね！

こっからは主観的な話ですが，初めてPythonを入れようとするときにAnacondaをインストールしようとしたら色々訳わかんなくてしんどかったためAnacondaよりもなんだかんだ普通にPython入れたほうが捗ると思います・・・

**Comment by reud** [comment]
```
ネットでは同じような問題が起きた際、対処法として
https://blog.cles.jp/item/10259
以上の記事のような方法が紹介されていて、PyLineNotifyではこの方法を使うことはできますか？
```
SSL証明書が原因ではなく，Pythonで一般的に使われるrequestsライブラリとAnaconda/Minicondaの相性が悪いため起きている問題だと考えられますのでその解決方法は使えないと考えられます．

**Comment by reud** [comment]
解決したら閉めますので教えてくださいね！

**Comment by reud** [comment]
解決したようなので閉めます

**Comment by kanade9** [comment]
返信が遅くなりすみませんでした。
解決しました。ありがとうございました。
